"use client";
import dynamic from "next/dynamic";

export const Breadcrumb = dynamic(() => import("./Breadcrumb"), { ssr: false });
export const DataTables = dynamic(() => import("./DataTables"), { ssr: false });
export const FormModal = dynamic(() => import("./FormModal"), { ssr: false });
export const InfoModal = dynamic(() => import("./InfoModal"), { ssr: false });
export const List = dynamic(() => import("./List"), { ssr: false });
export const LoadingOverlay = dynamic(() => import("./LoadingOverlay"), { ssr: false });
export const Tooltip = dynamic(() => import("./Tooltip"), { ssr: false });
export const TooltipInfo = dynamic(() => import("./TooltipInfo"), { ssr: false });
export const PrintButton = dynamic(() => import("./PrintButton"), { ssr: false });
export const DaftarNominatif = dynamic(() => import("./DaftarNominatif"), { ssr: false });
export const Snackbar = dynamic(() => import("./Snackbar"), { ssr: false });
export const StatCard = dynamic(() => import("./StatCard"), { ssr: false });
export const MonthlySchedule = dynamic(() => import("./MonthlySchedule"), { ssr: false });
export const VerifBiayaPerjalanan = dynamic(() => import("./VerifBiayaPerjalanan"), { ssr: false });
export const NotificationDashboard = dynamic(() => import("./NotificationDashboard"), { ssr: false });
export const StatusBadge = dynamic(() => import("./StatusBadge"), { ssr: false });
export const InfoPerjalanan = dynamic(() => import("./InfoPerjalanan"), { ssr: false });
export const PreviewPDF = dynamic(() => import("./PreviewPDF"), { ssr: false });
export const DropdownFilter = dynamic(() => import("./DropdownFilter"), { ssr: false });
export const DaftarNominatifAjuan = dynamic(() => import("./DaftarNominatifAjuan"), { ssr: false });
export const SearchBar = dynamic(() => import("./SearchBar"), { ssr: false });